#!/bin/bash

# This script should be runnable in any environment where the 'docker' command
# line will tell an engine to do things.

set -e;

docker build -t base -f base.Dockerfile .;
docker build -t build -f build.Dockerfile .;

mkdir -p build/wheelhouse;

CACHING_ARGS="$(
    if [ -n "${PIP_INDEX_URL}" ]; then
        echo "-e=PIP_TRUSTED_HOST=docker.for.mac.localhost -e=PIP_INDEX_URL=$(echo $PIP_INDEX_URL | sed s/127.0.0.1/docker.for.mac.localhost/g)"; # as per 'docker for mac' networking guide alias
    fi;
)";

echo "$argz";

tar cjf - -X .dockerignore . | \
    docker run --rm -i $CACHING_ARGS build | \
    (cd build/wheelhouse; tar xjf -);

docker build -t infratwisted/lists .;

if [ -n "${DOCKER_PUSH_PASSWORD}" ]; then
    docker login -u "${DOCKER_PUSH_USER}" -p "${DOCKER_PUSH_PASSWORD}";
fi;

function dvc.volname () {
    # Allow for setting VOLUME_PREFIX so that we can map host paths if we want,
    # for development.
    local VOLUME_NAME="$1"; shift;
    echo -n "${VOLUME_PREFIX:+${VOLUME_PREFIX}/}${VOLUME_NAME}";
}

if "${DEPLOYING}"; then
    docker push infratwisted/lists; # XXX fixme: 'hyper load'?
    if hyper fip detach lists-container; then
        echo successfully detached;
    else
        echo detach failed;
    fi;
    RUNNER="hyper run --size=s4 ";
    STOPPER="hyper rm -f ";
else
    RUNNER="docker run";
    STOPPER="docker rm -f ";
fi;

if $STOPPER lists-container; then
    echo successfully stopped;
else
    echo stop failed;
fi;

$RUNNER -e MAILGUN_API_KEY -e NO_RENEW --detach \
      --name lists-container --restart=always \
      -v "$(dvc.volname lists-tls)":/certificates \
      -v "$(dvc.volname lists-database)":/database \
      -v "$(dvc.volname lists-messages)":/legacy-mailman-archive \
      -p 443:8443 \
      infratwisted/lists;

if "${DEPLOYING}"; then
    hyper fip attach 209.177.93.178 lists-container;
fi;
