#!/bin/bash

# Set up an authenticated Carina environment for travis.

curl -L "https://download.getcarina.com/carina/latest/$(uname -s)/$(uname -m)/carina" -o carina
chmod a+x ./carina
curl -sL https://download.getcarina.com/dvm/latest/install.sh | sh
source ~/.dvm/dvm.sh
./carina credentials lists
. ~/.carina/clusters/"${CARINA_USERNAME}"/lists/docker.env;
dvm use;

# Delegate to docker-building script.

. ./buildandrun;
