#!/bin/bash

curl -L "https://download.getcarina.com/carina/latest/$(uname -s)/$(uname -m)/carina" -o carina
chmod a+x ./carina
curl -sL https://download.getcarina.com/dvm/latest/install.sh | sh
source ~/.dvm/dvm.sh
./carina credentials lists
. ~/.carina/clusters/"${CARINA_USERNAME}"/lists/docker.env;
dvm use;

docker build -t base -f base.Dockerfile .;
docker build -t build -f build.Dockerfile .;

mkdir -p build/wheelhouse;

tar cjf - . | docker run --rm build | (cd build/wheelhouse; mkdir tar xjf -);

docker build -t lists.twistedmatrix.com .;
docker rm -f lists-container;
docker run --detach --name lists-container --restart=always -p 8080:8080 lists.twistedmatrix.com;
