#!/bin/bash

mkdir -p volumes;

# In development, get your own TLS certs, and somehow inject them into the
# volume.
NO_RENEW=yes \
        TWISTED_USER_ID="$(id -u)" \
        TLS_HOSTNAME="$(hostname -f)" \
        VOLUME_PREFIX="$PWD/volumes" \
        bash -x buildandrun;
