#!/bin/bash

# quick syntax check before we spend a minute waiting for builds
if ! pyflakes src/txlists; then
    echo "pyflakes failed";
    exit 1;
fi;

mkdir -p volumes;

# In development, get your own TLS certs, and somehow inject them into the
# volume.
NO_RENEW=yes \
        TWISTED_USER_ID="$(id -u)" \
        TLS_HOSTNAME="$(hostname -f)" \
        VOLUME_PREFIX="$PWD/volumes" \
        DEPLOYING=false \
        bash -x buildandrun;

docker logs -f lists-container;
